#!/usr/bin/env bash

SRC_PATTERN="guides/"
CHANGES=$(git diff --cached --name-only | grep "$SRC_PATTERN")
FILE_IGNORED_PAGES=".remarkignore"
FILES_NOT_IGNORED=()

readonly CHANGES
readonly FILE_IGNORED_PAGES
readonly SRC_PATTERN

# Find the files not declared in `$FILE_IGNORED_PAGES`
for translated in $CHANGES; do
  if ! grep --quiet "$translated" "$FILE_IGNORED_PAGES"; then
    FILES_NOT_IGNORED+=("$translated")
  fi
done

if [ ${#FILES_NOT_IGNORED[@]} -ne 0 ]; then
  # Warn user about files missing from `$FILE_IGNORED_PAGES`

  echo
  echo "******* WARNING *******"
  echo
  echo "You have translated these files:"
  echo

  for file_path in "${FILES_NOT_IGNORED[@]}"; do
    printf '%s\n' "- $file_path"
    echo "!$file_path" >> $FILE_IGNORED_PAGES
  done

  echo
  echo "But they were not present in \`$FILE_IGNORED_PAGES\`, so we have added them for you."
  echo
  echo "All you have to do now is:"
  echo "1. To make sure entries are listed in alphabetical order"
  echo "2. To stage and commit \`$FILE_IGNORED_PAGES\`"
  echo
  echo "***********************"
  echo

  exit 1

fi
