#!/bin/sh
SRC_PATTERN="guides/release/"
changes=`git diff --cached --name-only | grep "$SRC_PATTERN"`
for translated in $changes; do
  while read -r line; do
    if [ "!$translated" = "$line" ]; then
      exit 0
    fi
  done < ".remarkignore"
  echo "******* WARNING *******"
  echo "Check your spelling ;)"
  echo You translated the file:
  echo $translated
  echo But it is not present in .remarkignore
  echo "***********************"
done
exit 0
