name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 12.19
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test-node:
    name: Test node-tests
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Setup
        run: npm run setup

      - name: Test
        run: npm run test:node
